### ISSUE TITLE
ERROR in funannotate setup

### ISSUE THREAD

**Issue by wangnan9394** [reslp/funannotate-docker#1]
hello,
I am start to build the four programs in funannotate-docker, and I have two directories /database/ and  /external/ in /data/. And gm_et_linux_64 (file) , signalp-4.1(directory) and interproscan-5.46-81.0(directory) in external and change the signalp script. 

Firstly, I use  `docker run --rm -it -v $PWD/database:/root/database -v $PWD/external:/data/external -v $PWD:/data -w /data --entrypoint /bin/bash reslp/funannotate:latest` to inside the container.
Then set the FUNANNOTATE_DB environment variable `export FUNANNOTATE_DB=/root/database`
When i use the command "funannotate setup -i all -f",there is an error,
I want to use a command like this `funannotate predict -i mygenome.fa -o output_folder -s "Aspergillus nidulans" --pasa_gff mypasamodels.gff3:8 --other_gff prediction1.gff3:5 prediction2.gff3:1`

ERROR：
```
-------------------------------------------------------
[07:41 PM]: OS: linux2, 112 cores, ~ 1056 GB RAM. Python: 2.7.17
[07:41 PM]: Running 1.7.4
[07:41 PM]: Database location: /root/database
[07:41 PM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 660, in <module>
    main()
  File "/usr/local/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 652, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 132, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: 'NoneType' object is not iterable

```
setupDB.py seems not work, but i didn't know how to fix ,could you help me？

**Comment by reslp** [comment]
Hi,

I just tested this. These steps should fix the problem with funannotate setup:

1. Remove the database folder completely before staring the container: $ sudo rm -rf database
2. The bindpoint for the funannotate database is /data/database. There is no need to change the env variable inside the container. (I see that this is specified differently in the README. I will fix this)
3. Use the git_clone version of the container. It contains a fix in funannotate during parsing the downloaded interpro database.

This is the command I used and it worked:

```
$ docker run --rm -it -v $PWD/database:/data/database -v $PWD/external:/data/external -v $PWD:/data -w /data --entrypoint /bin/bash reslp/funannotate:git_clone
root@f68f1926c6b5:~# funannotate setup -i all
-------------------------------------------------------
[07:38 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.17
[07:38 AM]: Running 1.7.4
[07:38 AM]: Database location: /data/database
[07:38 AM]: Parsing Augustus pre-trained species and porting to funannotate
[07:38 AM]: Downloading Merops database
[07:38 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1957603
[07:38 AM]: Building diamond database
[07:38 AM]: MEROPS Database: version=12.0 date=2017-10-04 records=5,009
[07:38 AM]: Downloading UniProtKB/SwissProt database
[07:38 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 89505269
[07:39 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt Bytes: 151
[07:39 AM]: Building diamond database
[07:39 AM]: UniProtKB Database: version=2020_04 date=2020-08-12 records=563,082
[07:39 AM]: Downloading dbCAN database
[07:39 AM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V7.txt Bytes: 87673048
[07:41 AM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07312018.fam-activities.txt Bytes: 59480
[07:41 AM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-old@UGA/readme.txt Bytes: 7507
[07:41 AM]: Creating dbCAN HMM database
[07:41 AM]: dbCAN Database: version=9.0 date=2020-08-04 records=607
[07:41 AM]: Downloading Pfam database
[07:41 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.hmm.gz Bytes: 274119400
[07:45 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.clans.tsv.gz Bytes: 335058
[07:45 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam.version.gz Bytes: 116
[07:45 AM]: Creating Pfam HMM database
[07:45 AM]: Pfam Database: version=33.1 date=2020-04 records=18,259
[07:45 AM]: Downloading Repeat database
[07:45 AM]: Downloading: https://osf.io/vp87c/download?version=1 Bytes: 6325661
[07:45 AM]: Building diamond database
[07:45 AM]: Repeat Database: version=1.0 date=2020-09-07 records=11,950
[07:45 AM]: Downloading GO Ontology database
[07:45 AM]: Downloading: http://purl.obolibrary.org/obo/go.obo Bytes: 33763947
[07:45 AM]: GO ontology version=2020-08-11 date=2020-08-11 records=47,224
[07:45 AM]: Downloading MiBIG Secondary Metabolism database
[07:45 AM]: Downloading: https://dl.secondarymetabolites.org/mibig/mibig_prot_seqs_1.4.fasta Bytes: 21244378
[07:45 AM]: Building diamond database
[07:45 AM]: MiBIG Database: version=1.4 date=2020-09-07 records=31,023
[07:45 AM]: Downloading InterProScan Mapping file
[07:45 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro.xml.gz Bytes: 25703455
[07:46 AM]: InterProScan XML: version=81.0 date=2020-08-13 records=37,821
[07:46 AM]: Downloading pre-computed BUSCO outgroups
[07:46 AM]: Downloading: https://osf.io/r9sne/download?version=1 Bytes: 2374032
[07:46 AM]: BUSCO outgroups: version=1.0 date=2020-09-07 records=8
[07:46 AM]: Downloaded curated gene names and product descriptions
[07:46 AM]: Downloading: https://raw.githubusercontent.com/nextgenusfs/gene2product/master/ncbi_cleaned_gene_products.txt Bytes: 1344149
[07:46 AM]: Gene2Product: version=1.64 date=2020-08-25 records=33,640
[07:46 AM]: Downloading busco models: dikarya
[07:46 AM]: Downloading: https://osf.io/av6f8/download?version=1 Bytes: 66199252
root@f68f1926c6b5:~# funannotate database

Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      33.1         2020-04            18259   228db640818af54066a1c23404a3ba38
  gene2product      text        1.64         2020-08-25         33640   aa985b947a9758cc696421923f654a27
  interpro          xml         81.0         2020-08-13         37821   ec10ff5e4d6f7fa4982ce00c1c6335e9
  dbCAN             hmmer3      9.0          2020-08-04           607   51c724c1f9ac45687f08d0faa689ed58
  busco_outgroups   outgroups   1.0          2020-09-07             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          5009   a6dd76907896708f3ca5335f58560356
  mibig             diamond     1.4          2020-09-07         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2020_04      2020-08-12        563082   da5725f3aa16b176d6dcf4e7ba7c1ea1
  go                text        2020-08-11   2020-08-11         47224   e57e1d7dd6f503cc87d77dcc6ec7d903
  repeats           diamond     1.0          2020-09-07         11950   4e8cafc3eea47ec7ba505bb1e3465d21

To update a database type:
	funannotate setup -i DBNAME -d /data/database --force

To see install BUSCO outgroups type:
	funannotate database --show-outgroups

To see BUSCO tree type:
	funannotate database --show-buscos

root@f68f1926c6b5:~# 

```

Please let me know if this works now.

cheers,

Philipp

**Comment by wangnan9394** [comment]
Dear Philipp,


Thanks for your advise.
I have tested by your guide, but seems the same problem. When I use the command "funannotate setup -i all", it start to download some data. However an error still comes.


root@b9422912bb74:~# funannotate setup -i all
-------------------------------------------------------
......
......
......
[05:48 PM]: InterProScan XML: version=81.0 date=2020-08-13 records=37,821
[05:48 PM]: Downloading pre-computed BUSCO outgroups
[05:48 PM]: BUSCO outgroups: version=1.0 date=2020-09-12 records=8
[05:48 PM]: Downloaded curated gene names and product descriptions
Traceback (most recent call last):
File "/usr/local/bin/funannotate", line 660, in <module>main()
File "/usr/local/bin/funannotate", line 650, in mainmod.main(arguments)
File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 672, in maincuratedDB(DatabaseInfo, args.force, args=args)
File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 456, in curatedDB download(resources.DBURL.get('gene2product'), curatedFile)
File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 66, in download    u = urllib2.urlopen(url)
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen    return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 429, in open   response = self._open(req, data)]
File "/usr/lib/python2.7/urllib2.py", line 447, in _open    '_open', req)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain    result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 1241, in https_opencontext=self._context) 
File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open    raise URLError(err)urllib2.
URLError: <urlopen error [Errno 101] Network is unreachable>
 
And continue to use command "funannotate setup -i all" again.


root@b9422912bb74:~# funannotate setup -i all
-------------------------------------------------------
[07:41 PM]: OS: linux2, 112 cores, ~ 1056 GB RAM. Python: 2.7.17
[07:41 PM]: Running 1.7.4
[07:41 PM]: Database location: /data/database
[07:41 PM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 660, in <module>
    main()
  File "/usr/local/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 656, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 132, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: 'NoneType' object is not iterable


I notice that error information ' [Errno 101] Network is unreachable', I guess there are some faults in obtaining the database. But I didn't know how to fix it. And I change another machine and test in Centos system, there is the same problem.


I appreciate your help very much. :)


Bests,
Nan


















At 2020-09-07 15:55:56, "Philipp Resl" <notifications@github.com> wrote:

Hi,

I just tested this. These steps should fix the problem with funannotate setup:

Remove the database folder completely before staring the container: $ sudo rm -rf database
The bindpoint for the funannotate database is /data/database. There is no need to change the env variable inside the container. (I see that this is specified differently in the README. I will fix this)
Use the git_clone version of the container. It contains a fix in funannotate during parsing the downloaded interpro database.

This is the command I used and it worked:

$ docker run --rm -it -v $PWD/database:/data/database -v $PWD/external:/data/external -v $PWD:/data -w /data --entrypoint /bin/bash reslp/funannotate:git_clone
root@f68f1926c6b5:~# funannotate setup -i all
-------------------------------------------------------
[07:38 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.17
[07:38 AM]: Running 1.7.4
[07:38 AM]: Database location: /data/database
[07:38 AM]: Parsing Augustus pre-trained species and porting to funannotate
[07:38 AM]: Downloading Merops database
[07:38 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1957603
[07:38 AM]: Building diamond database
[07:38 AM]: MEROPS Database: version=12.0 date=2017-10-04 records=5,009
[07:38 AM]: Downloading UniProtKB/SwissProt database
[07:38 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 89505269
[07:39 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt Bytes: 151
[07:39 AM]: Building diamond database
[07:39 AM]: UniProtKB Database: version=2020_04 date=2020-08-12 records=563,082
[07:39 AM]: Downloading dbCAN database
[07:39 AM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V7.txt Bytes: 87673048
[07:41 AM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07312018.fam-activities.txt Bytes: 59480
[07:41 AM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-old@UGA/readme.txt Bytes: 7507
[07:41 AM]: Creating dbCAN HMM database
[07:41 AM]: dbCAN Database: version=9.0 date=2020-08-04 records=607
[07:41 AM]: Downloading Pfam database
[07:41 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.hmm.gz Bytes: 274119400
[07:45 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.clans.tsv.gz Bytes: 335058
[07:45 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam.version.gz Bytes: 116
[07:45 AM]: Creating Pfam HMM database
[07:45 AM]: Pfam Database: version=33.1 date=2020-04 records=18,259
[07:45 AM]: Downloading Repeat database
[07:45 AM]: Downloading: https://osf.io/vp87c/download?version=1 Bytes: 6325661
[07:45 AM]: Building diamond database
[07:45 AM]: Repeat Database: version=1.0 date=2020-09-07 records=11,950
[07:45 AM]: Downloading GO Ontology database
[07:45 AM]: Downloading: http://purl.obolibrary.org/obo/go.obo Bytes: 33763947
[07:45 AM]: GO ontology version=2020-08-11 date=2020-08-11 records=47,224
[07:45 AM]: Downloading MiBIG Secondary Metabolism database
[07:45 AM]: Downloading: https://dl.secondarymetabolites.org/mibig/mibig_prot_seqs_1.4.fasta Bytes: 21244378
[07:45 AM]: Building diamond database
[07:45 AM]: MiBIG Database: version=1.4 date=2020-09-07 records=31,023
[07:45 AM]: Downloading InterProScan Mapping file
[07:45 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro.xml.gz Bytes: 25703455
[07:46 AM]: InterProScan XML: version=81.0 date=2020-08-13 records=37,821
[07:46 AM]: Downloading pre-computed BUSCO outgroups
[07:46 AM]: Downloading: https://osf.io/r9sne/download?version=1 Bytes: 2374032
[07:46 AM]: BUSCO outgroups: version=1.0 date=2020-09-07 records=8
[07:46 AM]: Downloaded curated gene names and product descriptions
[07:46 AM]: Downloading: https://raw.githubusercontent.com/nextgenusfs/gene2product/master/ncbi_cleaned_gene_products.txt Bytes: 1344149
[07:46 AM]: Gene2Product: version=1.64 date=2020-08-25 records=33,640
[07:46 AM]: Downloading busco models: dikarya
[07:46 AM]: Downloading: https://osf.io/av6f8/download?version=1 Bytes: 66199252
root@f68f1926c6b5:~# funannotate database

Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      33.1         2020-04            18259   228db640818af54066a1c23404a3ba38
  gene2product      text        1.64         2020-08-25         33640   aa985b947a9758cc696421923f654a27
  interpro          xml         81.0         2020-08-13         37821   ec10ff5e4d6f7fa4982ce00c1c6335e9
  dbCAN             hmmer3      9.0          2020-08-04           607   51c724c1f9ac45687f08d0faa689ed58
  busco_outgroups   outgroups   1.0          2020-09-07             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          5009   a6dd76907896708f3ca5335f58560356
  mibig             diamond     1.4          2020-09-07         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2020_04      2020-08-12        563082   da5725f3aa16b176d6dcf4e7ba7c1ea1
  go                text        2020-08-11   2020-08-11         47224   e57e1d7dd6f503cc87d77dcc6ec7d903
  repeats           diamond     1.0          2020-09-07         11950   4e8cafc3eea47ec7ba505bb1e3465d21

To update a database type:
	funannotate setup -i DBNAME -d /data/database --force

To see install BUSCO outgroups type:
	funannotate database --show-outgroups

To see BUSCO tree type:
	funannotate database --show-buscos

root@f68f1926c6b5:~# 



Please let me know if this works now.

cheers,

Philipp

**Comment by reslp** [comment]
Hi, sorry for the late reply. Do you still have this problem? You could now try to use a newer version of funannotate and see of the error still occurs. From what I see is it could also be that the respective file was not available (maybe there was a network problem).

cheers,

Philipp

**Comment by reslp** [comment]
I am closing this now. Please reopen if this is still an issue.
